name: df -h

on:
  workflow_dispatch:
  watch:
    types: [started]
    
jobs:
  clean:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Run commands
      run: |
        ls $HOME
        df -h
        