name: clean

on:
  workflow_dispatch:
  watch:
    types: [started]
    
jobs:
  clean:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
    
    - name: List 100 largest packages
      run: |
        echo "=============================================================================="
        echo "Listing 200 largest packages"
        echo "=============================================================================="

        # echo "Listing 200 largest packages"
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h

