name: ls

on:
  workflow_dispatch:
  watch:
    types: [started]
    
jobs:
  clean:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Run commands
      run: |
        pwd
        ls
        mkdir -p im/in/here
        cd im/in/here
        touch bruh
        ls
        echo
        echo
        
    - name: Run commands 2
      run: |
        pwd
        ls
