name: nproc --all

on:
  workflow_dispatch:
  watch:
    types: [started]
    
jobs:
  nproc:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Run commands
      run: nproc --all
        