# This is taken from https://github.com/Area69Lab/Recovery-Builder-NoKernel
# All credits goes to above repo

name: Building recovery

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  TZ: Asia/Kuala_Lumpur
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
  
    - name: Docker
      run: docker rmi `docker images -q`

    - name: Cleaning up runner
      uses: rokibhasansagar/slimhub_actions@main

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 8
 
    - name: Initializing environment
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
        git config --global user.name "Hakimi0804"
        git config --global user.email "hakimifirdaus944@gmail.com"
        sudo -E apt-get clean
        sudo -E apt-get update
        sudo -E apt-get install bc build-essential zip curl libstdc++6 git wget python3 python-is-python3 gcc clang libssl-dev repo rsync flex bison aria2
        df -h
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo


    - name: Standalone script take over https://github.com/Hakimi0804/OrangeFox-CI/blob/main/pbrp-build.sh
      run: |
        wget https://raw.githubusercontent.com/Hakimi0804/OrangeFox-CI/main/pbrp-build.sh
        bash pbrp-build.sh
