name: git cherry-pick

on:
  workflow_dispatch:
  watch:
    types: [started]

env:
  MANIFEST: https://github.com/PitchBlackRecoveryProject/manifest_pb.git
  MANIFEST_BRANCH: android-11.0
  DEVICE: RMX2001
  DT_LINK: https://github.com/Hakimi0804/android_device_realme_RMX2001-pbrp
  DT_BRANCH: android-11.0
  DT_PATH: device/realme/RMX2001
  TARGET: pbrp
  TZ: Asia/Kuala_Lumpur

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@master

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
        
    - name: repo sync
      run: |
        sudo -E apt-get -qq install bc build-essential zip curl libstdc++6 git wget python gcc clang libssl-dev repo rsync flex bison aria2
        sudo curl --create-dirs -L -o /usr/local/bin/repo -O -L https://storage.googleapis.com/git-repo-downloads/repo
        sudo chmod a+rx /usr/local/bin/repo
        mkdir work
        repo init -u $MANIFEST -b $MANIFEST_BRANCH --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
        repo sync -j4
        
    - name: Checks
      run: |
        cd platform
        find -type d -name '*.git'
